
  - name: customer_metrics
    description: |
      Aggregated customer metrics for dashboards
      - Grouped by country, quality tier, lifecycle stage
      - Pre-calculated percentages
      - Updated with each dbt run
    columns:
      - name: country
        description: Customer country
      - name: total_customers
        description: Count of customers in this segment
        tests:
          - not_null
      - name: pct_valid_email
        description: Percentage with valid email format
      - name: pct_complete_profile
        description: Percentage with complete profiles

  - name: data_quality_report
    description: |
      Data quality monitoring across all layers
      - Tracks quality metrics from raw to marts
      - Alert-ready for data quality issues
    columns:
      - name: layer
        description: Data layer (staging/intermediate/marts)
        tests:
          - not_null
      - name: dedup_status
        description: Deduplication health check
        tests:
          - accepted_values:
              values: ['✅ OK', '⚠️ CHECK']

  - name: vw_customers_powerbi
    description: |
      Simplified customer view for Power BI
      - Only essential columns
      - No complex types
      - Optimized for dashboard queries

  - name: vw_metrics_powerbi
    description: |
      Pre-aggregated metrics for Power BI
      - Fast dashboard loading
      - Country and quality tier breakdowns
